services:
  - type: web
    name: alexpiku
    env: node
    branch: main
    repo: https://github.com/Piku090909/Jarvis-md.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ᴊᴀʀᴠɪꜱ;ʟᴏᴋɪ-xᴇʀ;https://i.imgur.com/VIpl3q5.mp4
      - key: WARN_COUNT
        value: 3
      - key: AUTO_STATUS_VIEWS
        value: false
      - key: MEDIA_DATA
        value: ʟɪꜱᴛ ᴍᴇɴᴜ;alexpiku;https://telegra.ph/file/83b9c9d01c9c571501d8e.mp4
      - key: HANDLER
        value: ✓
      - key: WORK_TYPE
        value: private
      - key: SERVER
        value: render
      - key: STICKER_PACKNAME
        value: alex;piku
      - key: AUDIO_DATA
        value: alex;piku;https://telegra.ph/file/83b9c9d01c9c571501d8e.mp4
      - key: SUDO
        value: 918536881026
      - key: SERVERURL
        value:
      - key: DATABASE_URL
        sync: false
